name: Update README.md

on:
  workflow_call:

permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4

      - name: checkout readme content
        uses: actions/checkout@v4
        with:
          repository: MaximumFX/tk-readme-generator
          path: ./tmp/tk-readme-generator

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r ./tmp/tk-readme-generator/requirements.txt

      - name: execute py script
        run: python ./tmp/tk-readme-generator/tk-readme-generator.py info.yml -o

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git diff-index --quiet HEAD || (git commit -a -m "Update README.md" --allow-empty)

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
